server:
  port: 1306
  servlet:
    context-path: /api

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: "${JWT_SECRET:872c871a1ab996919a3e97145ece2418bb837cadbd69387d96cd45eef831f239}"
  expiration: "${JWT_EXPIRATION:86400000}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: false
logging:
  level:
    root: info
  file:
    name: target/toeicute.log


application:
  ignored:
    urls:
      - /user/get-captcha
      - /user/register
      - /user/authenticate
      - /user/forgot-password
      - /user/confirm-otp
      - /user/reset-password
      - /user/test
      - /v3/api-docs
      - /v3/api-docs/**